
name: Build

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USE_STUBBED_LIBS: 1
      RELEASE_VERSION: ${{ format('{0}-{1}', github.sha, github.event_name == 'pull_request' && github.head_ref || github.ref_name) }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Grant execute permissions for build script
      run: chmod +x build.sh

    - name: Build
      run: ./build.sh --target=BuildThunderstore

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: thunderstore-package
        path: CustomEmotesAPI/bin/Debug/netstandard2.1/upload/
        retention-days: 15